sudo: required

language: bash

dist: xenial

services:
  - docker

script:
  - TAG="latest"
  - CONT_NAME="webssh-wetty"
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"/build
  - docker images
  - docker push cultclassik/$CONT_NAME:$TAG
